### ISSUE TITLE
Explore Flutter as Alternative to React Native for PlatIPal

### ISSUE THREAD

**Issue by dror-llm** [drorm/vmpilot#92]
# Explore Flutter as Alternative to React Native for PlatIPal

## Overview

We want to explore Flutter as an alternative mobile framework to compare development experience, performance, and capabilities.

## Goals

-   **Compare development experience**: Flutter vs React Native for our bilingual language learning use case
-   **Evaluate performance**: App startup, UI responsiveness, bundle size
-   **Assess platform integration**: How well Flutter integrates with native speech services
-   **Test package ecosystem**: Flutter packages vs React Native modules for our needs

### Core Features to Implement

1. **Basic App Structure**

    - Welcome/onboarding screen with language selection
    - Home screen with main navigation
    - Settings screen
    - Clean Material 3 UI design

2. **Navigation**

    - Use `go_router` for modern declarative routing
    - Bottom navigation or drawer navigation

3. **Internationalization**

    - English/Spanish language switching
    - Use `flutter_localizations` and `intl` packages
    - Persistent language preference

4. **State Management**
    - Use Riverpod for simple, reactive state management
    - Language preference state

### Technical Stack

```yaml
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    go_router: ^14.0.0
    riverpod: ^3.0.0
    flutter_riverpod: ^3.0.0
    intl: ^0.19.0
    google_fonts: ^6.2.0
    shared_preferences: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
```

### Project Structure

```
flutter_platipal/
├── lib/
│   ├── main.dart
│   ├── app.dart
│   ├── screens/
│   │   ├── welcome_screen.dart
│   │   ├── home_screen.dart
│   │   └── settings_screen.dart
│   ├── widgets/
│   │   └── language_selector.dart
│   ├── providers/
│   │   ├── language_provider.dart
│   │   └── theme_provider.dart
│   ├── l10n/ (internationalization)
│   │   ├── app_en.arb
│   │   └── app_es.arb
│   └── routing/
│       └── app_router.dart
├── assets/
│   └── fonts/
└── pubspec.yaml
```

## Success Criteria

-   [ ] App builds and runs on Android
-   [ ] Smooth navigation between screens
-   [ ] Language switching works (English ↔ Spanish)
-   [ ] Clean, modern Material 3 UI
-   [ ] Performance feels responsive
-   [ ] Development experience is smooth (hot reload, debugging)

## Comparison Metrics

After implementation, we'll compare:

### Development Experience

-   Setup time and complexity
-   Hot reload speed and reliability
-   Debugging capabilities
-   Code organization and maintainability

### Performance

-   App startup time
-   UI responsiveness and animations
-   APK/bundle size
-   Memory usage

### Platform Integration

-   How native the app feels
-   Ease of accessing platform features
-   Build process complexity

### Package Ecosystem

-   Availability of packages for our needs
-   Package quality and maintenance
-   Documentation and community support

## Next Steps

1. Initialize Flutter project in `/flutter` directory
2. Implement basic screens and navigation
3. Add internationalization support
4. Apply Material 3 theming
5. Test on Android devices
6. Document findings and comparisons
7. Decide on framework choice for full implementation
